# version isn't needed as of 2020 for docker compose CLI. 
# All 2.x and 3.x features supported
# version: '2'

# based off compose-sample-2, only we build nginx.conf into image
# uses sample HTML static site from https://startbootstrap.com/themes/agency/

services:
  proxy:
    build:
      context: .  #build the dockerfile in this current directory that it's in 
      dockerfile: nginx.Dockerfile
    image: nginx-custom  # i want it named nginx-custom when it gets built
    ports:
      - '80:80'
  web:
    image: httpd
    volumes:
      - ./html:/usr/local/apache2/htdocs/ #Mounted some HTml source files that i have into apache2
